name: test

on:
  push:
    branches: [ feature/github-actions ]
  pull_request:
    branches: [ feature/github-actions ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_build_rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      working-directory: ./lib_core
      run: cargo test --verbose
    - run: rustup target add wasm32-unknown-unknown
    - name: Build
      working-directory: ./lib_core
      run: cargo build --verbose

  test_elixir:
    needs: test_and_build_rust
    runs-on: ubuntu-latest
    steps:
      - name: Get latest WASM file
        working-directory: ./elixir/core
        run: cp ../../lib_core/target/wasm32-unknown-unknown/release/lib_core.wasm
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '25'
          elixir-version: '1.14.0'
          experimental-otp: true
