name: test

on:
  push:
    branches: [ feature/github-actions ]
  pull_request:
    branches: [ feature/github-actions ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup target add wasm32-unknown-unknown
    - name: Build
      working-directory: ./core
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./core
      run: cargo test --verbose
    - uses: actions/setup-elixir@v1
      with:
        otp-version: '25'
        elixir-version: '1.14.0'
