name: test

on:
  push:
    branches: [ feature/github-actions ]
  pull_request:
    branches: [ feature/github-actions ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_build_rust:
    runs-on: ubuntu-latest
    env:
      working-directory: ./lib_core
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      working-directory: ${{env.working-directory}}
      run: cargo test --verbose
    - run: rustup target add wasm32-unknown-unknown
    - name: Build
      working-directory: ${{env.working-directory}}
      run: cargo build --release --target wasm32-unknown-unknown --verbose
    - uses: actions/upload-artifact@master
      with:
        name: core-wasm
        path: lib_core/target/wasm32-unknown-unknown/release/lib_core.wasm

  test_elixir:
    needs: test_and_build_rust
    runs-on: ubuntu-latest
    env:
      working-directory: ./elixir/core
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: core-wasm
          path: priv/lib_core.wasm
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '25'
          elixir-version: '1.14.0'
          experimental-otp: true
      - run: mix deps.get
        working-directory: ${{env.working-directory}}
      - run: mix test
        working-directory: ${{env.working-directory}}
